libtransact/src/execution/adapter/mod.rs
libtransact/src/execution/adapter/test_adapter.rs
libtransact/src/execution/executer_internal.rs
libtransact/src/execution/mod.rs

Replace the callbacks with a trait called `ExecutionRegistry` (for the time being - if we add more methods, it will have to be renamed).
Additionally,
* Removes some internals from the public library API
* Removes the OnDoneCallback type alias, to allow the use of the `dyn` keyword.
Replacement for #33

Execution registry

---

libtransact/src/state/merkle.rs

There was a typo in 'pruning' previously.
Signed-off-by: Shawn T. Amundson <amundson@bitwise.io>

Fix name of merkle_trie_pruning_successors test

---

libtransact/src/lib.rs

These were necessarily with an older version of Rust, but are no longer
needed in current stable Rust (1.32.0).
Signed-off-by: Shawn T. Amundson <amundson@bitwise.io>

Remove unnecessary extern crate statements

---

libtransact/src/state/change_log.rs

The Successor impl had implementations for to_bytes/from_bytes, which
were not used and were not public functions. This was the only things
implemented on Successor, so removed the entire impl block.
This fixes a couple compiler warnings.
Signed-off-by: Shawn T. Amundson <amundson@bitwise.io>

Remove unused Successor impl

---

libtransact/Cargo.toml
libtransact/src/context/manager.rs
libtransact/src/context/mod.rs
libtransact/src/receipts.rs
libtransact/src/state/mod.rs

Reopening previous PR #31 
Adds initial implementation of the Context Manager and Context objects. This allows for Contexts to be created and altered with StateChanges. Also allows for the lookup of keys within Contexts and State.
Some functionality worth noting (and am open to other thoughts on how to implement this piece) is the addition of the `StateChangeResult` which is an enum based on the `StateChange` added to a Context. With a` StateChange::Set`, the `StateChangeResult` will return just the key that was set, and with a `StateChange::Delete`, the `StateChangeResult` will return the value that was deleted.
Also, the `drop_context` function is currently unimplemented as it seemed as though there could be more discussion on this function.

Add initial Context Manager

---

libtransact/src/state/merkle.rs

This PR 
- Refactors MerkleDatabase slightly to remove the use of Mutex wrapping root_node and root_hash. It creates a new struct MerkleState that wraps an LMDB database and implements the Read,
Write and Prune traits. MerkleState creates an instance of MerkleDatabase and call its methods
to perform read, write and prune operations.
- MerkleDatabase is renamed MerkleRadixTree. 
- Fix a few compiler warnings in the merkle test module

Remove mutex

---

libtransact/src/context/manager.rs
libtransact/src/execution/adapter/error.rs
libtransact/src/execution/adapter/test_adapter.rs
libtransact/src/execution/executer_internal.rs
libtransact/src/scheduler/mod.rs
libtransact/src/state/hashmap.rs
libtransact/src/state/merkle.rs
libtransact/src/state/mod.rs

Additionally, contains so other changes, such as removing the need for generic `Read` on the ContextManager, removing clone from `Read`, some context manager argument changes, and some error cleanup.

Implement a basic, lock-backed Threadsafe Context Manager

---

libtransact/src/handler/error.rs
libtransact/src/handler/mod.rs
libtransact/src/lib.rs

Add the transaction handler and context traits from the Sawtooth Rust
SDK, separating the errors into a submodule for clarity.
Signed-off-by: Peter Schwarz <pschwarz@bitwise.io>

Add transaction handler and context from rust sdk

---

libtransact/src/context/manager.rs
libtransact/src/context/mod.rs

Adds the get_transaction_receipt method to the Context Lifecycle trait to be used within the Scheduler module. 
Signed-off-by: Shannyn Telander <telander@bitwise.io>

Add get_transaction_receipt to Context Lifecycle

---

libtransact/src/context/error.rs
libtransact/src/context/manager.rs
libtransact/src/context/mod.rs

Moves the errors used in the ContextManager to a separate module.
Signed-off-by: Shannyn Telander <telander@bitwise.io>

Add ContextManager error module

---

libtransact/src/execution/adapter/error.rs
libtransact/src/execution/adapter/mod.rs
libtransact/src/execution/adapter/static_adapter.rs
libtransact/src/execution/adapter/test_adapter.rs
libtransact/src/execution/executer_internal.rs
libtransact/src/handler/mod.rs
libtransact/src/workload/command.rs
libtransact/src/workload/mod.rs

Implement a static execution adapter which takes TransactionHandlers and dispatches transaction pairs based on the transaction family they specify.
This handler runs on a background thread, and all operations are sent to it via a channel.
Additionally, this PR modifies several traits and type bounds to include send, which is required for these items to be passed to background threads.

Static Execution Adapter

---

libtransact/src/state/merkle.rs

Add a public constructor for the `MerkleState` wrapper, to enable library users to use the object.

Add Constructor to MerkleState

---

libtransact/src/execution/executer.rs

Implements the standard requirements for std::error::Error
Signed-off-by: Peter Schwarz <pschwarz@bitwise.io>

Implement std::error::Error for ExecuterError

---

libtransact/src/execution/executor/internal.rs
libtransact/src/execution/executor/mod.rs
libtransact/src/execution/executor/reader.rs
libtransact/src/scheduler/mod.rs
libtransact/src/scheduler/serial/execution.rs

This PR removes a level of indirection for the execution task completion notifications.  The notifier, which is currently Send, now also provides clone through a `clone_box` and `Clone` implementation for boxed notifiers.  This allows the notifier to be sent directly to the execution adapter, instead of indirectly via a sender.
This removes the additional thread needed to receive the notifications and forward them to the notifier.
It also removes the callback for removing the reader from the list in the executor, though this was not being actively executed and also contained a dead-lock.
The removal of this thread, and the simplification improves the CPU utilization of the executor dramatically.
Additionally,
- Reorders use statements to follow the convention of std, external crate and …

Simplify executor's use of notifiers

---

libtransact/src/execution/executor/internal.rs
libtransact/src/execution/executor/reader.rs

Replace `recv_timeout` with a shutdown signal as part of the commands sent to the Executor thread.
Additionally, it generalizes the `RegistrationExecutionEvent` to `ExectorCommand`, as it has long extended itself beyond its original purview.
`recv_timeout` is [buggy](https://github.com/rust-lang/rust/issues/39364) (this particular issue is mis-titled, as it has more to do with `recv_timeout`).

Remove use of recv_timeout

---

libtransact/src/context/manager/mod.rs
libtransact/src/context/manager/sync.rs

Separates the thread-safe ContextManager into a new file. Previously, this module was defined within the manager file. 
Signed-off-by: Shannyn Telander <telander@bitwise.io>

Separate thread-safe ContextManager module

---

libtransact/Cargo.toml

Version 0.1.0 was previously released, so updating the version number
in Cargo.toml to 0.1.1.
Signed-off-by: Shawn T. Amundson <amundson@bitwise.io>

Increment version to 0.1.1

---

bin/run_tests
libtransact/Cargo.toml
libtransact/src/lib.rs
libtransact/src/protocol/batch.rs
libtransact/src/protocol/receipt.rs
libtransact/src/protocol/transaction.rs
libtransact/src/sawtooth.rs
libtransact/src/scheduler/serial/core.rs
libtransact/src/state/change_log.rs

Add a Sawtooth compatibility layer for using Sawtooth Transaction Handlers via the Transact static execution adapters.  This includes an initial test (more forthcoming).
Note that this also adds a Rust feature to libtransact called `sawtooth-compat`, under which all of the sawooth-sdk related operations are organized (from a dependency perspective).  The tests (from a CI perspective), include running with the default features (i.e. no Sawtooth) and with sawtooth compatibility enabled.

Add Sawtooth Compatibility Layer

---

libtransact/Cargo.toml
libtransact/src/context/mod.rs
libtransact/src/database/btree.rs
libtransact/src/database/error.rs
libtransact/src/database/lmdb.rs
libtransact/src/database/mod.rs
libtransact/src/handler/mod.rs
libtransact/src/lib.rs
libtransact/src/protocol/batch.rs
libtransact/src/protocol/mod.rs
libtransact/src/protocol/transaction.rs
libtransact/src/protos.rs
libtransact/src/signing/error.rs
libtransact/src/signing/hash.rs
libtransact/src/signing/mod.rs

This PR adds simple documentation to all of the top level modules and some of the deeper modules.  It includes text for the library as a whole, and adds some license headers where missing.

Add some module documentation

---

libtransact/src/protocol/batch.rs
libtransact/src/sawtooth.rs
libtransact/src/scheduler/mod.rs
libtransact/src/scheduler/serial/core.rs
libtransact/src/scheduler/serial/execution.rs
libtransact/src/scheduler/serial/mod.rs
libtransact/src/scheduler/serial/shared.rs

- Improves how the serial scheudler's result callback is used
- Adds an error callback to the Scheduler trait that's used to report errors to the calling code
- Updates the serial scheduler to not panic; instead, it will propagate errors up where appropriate or simply log them

Scheduler callback and error updates

---

libtransact/src/scheduler/mod.rs
libtransact/src/scheduler/serial/core.rs
libtransact/src/scheduler/serial/mod.rs
libtransact/src/scheduler/serial/shared.rs

Updates the serial scheduler to return a None result when it is
finalized and all batches have been executed. This is triggered in two
ways:
1. When the scheduler is finalized, a notification is sent to the serial
scheduler's core thread; if there are no unscheduled batches and no
batch currently executing, the None result is sent.
2. If there are unscheduled batches or a batch is currently executing
when the scheduler is finalized, the scheduler will wait until all
batches have been executed, then send the None result.
Signed-off-by: Logan Seeley <seeley@bitwise.io>

Serial scheduler done
